### PR TITLE
Developer blog updates

### LINKED ISSUE #55: Debug logging shows an entry that requests to report this
Hi,  I frequently see entries in the log that devices become unavailable, typically when they are controlled by an automation action. This might have something to do with it:
FYI:

Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 19:17:56 (1 occurrences)
Last logged: 19:17:56

Entity None (<class 'custom_components.remeha_home.climate.RemehaHomeClimateEntity'>) implements HVACMode(s): off, heat, auto and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/msvisser/remeha_home/issues

### LINKED ISSUE #58: Deprecated functions, Rermeha failed
Logger: homeassistant.helpers.typing
Source: helpers/deprecation.py:206
First occurred: 7:47:36 PM (1 occurrences)
Last logged: 7:47:36 PM

HomeAssistantType was used from remeha_home, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'remeha_home' custom integration

### PR DESCRIPTION
**Pull request by dynasticorpheus**
[New entity features in Climate entity](https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded/)

[deprecated-backports-and-typing-aliases](https://developers.home-assistant.io/blog/2024/04/08/deprecated-backports-and-typing-aliases/)

Resolves #55 , #58

### CODE REVIEW

**Comment by Marck** [comment]
@msvisser can you take a look at this PR please?

**Comment by schinddo** [comment]
I have manually changed the files and everything is working well.

@msvisser In my option, you can merge the PR.

**Review by schinddo — APPROVED** [review]

**Comment by pepijndevos** [comment]
Would be good to apply these changes. For now I'll apply them in my own fork. Would you be open to giving some contributors commit access to spread the maintenance burden?

**Comment by msvisser** [comment]
I'm sorry for the delay merging this PR. I haven't really been using this integration much during the summer.

**Comment by pepijndevos** [comment]
No worries and thanks for the merge. I've only just started playing with our heat pump. I just wish it had a local API. Maybe next summer I'll try to help out sniffing the cooling API at least ;)

Sent from Proton Mail Android

-------- Original Message --------

**Pull request merged**
