### PR TITLE
Add power sensors

### PR DESCRIPTION
**Pull request by jurgenheine**
This is based on  PR of vipial1, but with separate controller so updates for power values are now done every 10 minutes

### CODE REVIEW

**Comment by p2923260** [comment]
Power sensor would be very useful for energy metering... polling every hour is more than enough as long as the physical sensor is not so precise anyway. Can you confirm when new version will be committed?

**Comment by m4v3r1ckNl** [comment]
Great stuff, would be nice to have "Electricalmeasurement" and "Polledsmartenergysummation" for both DWH and Heating. Is an interval possible (what is the max amount of pollings for the Remeha API?) to be used for automations for other appliances? I'm quite new with heatpumps, so lot of learning to do. Thanks.

> Power sensor would be very useful for energy metering... polling every hour is more than enough as long as the physical sensor is not so precise anyway. Can you confirm when new version will be committed?

**Comment by p2923260** [comment]
When will you merge and commit it?

**Comment by hugo-leij** [comment]
@msvisser can you give an update when this being merged? :D

**Comment by Marck** [comment]
Maybe a dumb question, but why add it in KWH and not m3? Is only that unit available from the API?

**Comment by msvisser** [comment]
I have release a beta version with consumption sensors as [v0.1.14b0](https://github.com/msvisser/remeha_home/releases/tag/0.1.14b0). Please check it out and let me know if it satisfies all needs.

**Comment by msvisser** [comment]
For further communication about the beta versions I've opened an issue #41.

**Comment by msvisser** [comment]
These features have been available in the 0.1.14 beta for a while now, so I'm closing this PR.

**Pull request closed without merging**
