### PR TITLE
Add sensors for gas consumption

### PR DESCRIPTION
**Pull request by vipial1**

### CODE REVIEW

**Comment by 055Richard** [comment]
I also like the Consumption sensors.

**Comment by nghaye** [comment]
The suggested pull request works great on my side, it could be great if it was merged !

**Comment by JeroenBeemster** [comment]
Upvote for merging from my side!

**Comment by msvisser** [comment]
This PR is looking good, but there is one thing I'm worried about. That is the fact that we are now also requesting the energy usage information every minute. This doubles the number of requests made to the API. We should maybe only update the energy consumption data every 10 minutes, and maybe not request it at all when a user does not want/need it.

**Comment by jurgenheine** [comment]
It would be nice if this is added. I was looking to add it myself too, but saw this PR. Your concern about the too frequently call the API I can understand. In my old Homey app with the depricated E-twist API I was doing it also once in 10 minutes. But is it possible to approve the PR and then add a counter and call the function every if the counter is higher then 9, instead of now every update, and of course reset the counter to 0 after call the update consumption function. Maybe a little bit spaghetti, but we have at least the energy consumption values.

**Comment by 055Richard** [comment]
I installeren the version of vipial1, workshops also for a etwist. Added energy delivered myself.

**Comment by p2923260** [comment]
@msvisser Power sensor would be very useful for energy metering... polling every hour is more than enough as long as the physical sensor is not so precise anyway. Can you confirm when new version will be committed?

@055Richard How to add manually the sensor until then?

**Comment by msvisser** [comment]
I have release a beta version with consumption sensors as [v0.1.14b0](https://github.com/msvisser/remeha_home/releases/tag/0.1.14b0). Please check it out and let me know if it satisfies all needs.

**Comment by p2923260** [comment]
Just downloaded and started testing it.
- At first startup it worked great and synched all the energy sensors
- Just note new sensors are disabled at startup, maybe better if enabled by default?
I will test in the next couple of days and let you know about daily refresh. Thanks again for your contribution.

**Comment by m4v3r1ckNl** [comment]
Downloaded and installed this release. Great update adding the energy sensors, much appreciated. Working without issues after reboot HA (Supervised). Will monitor the upcoming days/weeks as the data will be collected.

All systems are go!

**Comment by msvisser** [comment]
For further communication about the beta versions I've opened an issue #41.

**Comment by scifa123** [comment]
Hello, please how to install this update in HA?

**Comment by msvisser** [comment]
These features have been available in the 0.1.14 beta for a while now, so I'm closing this PR.

**Pull request closed without merging**
